name: Build and Deploy Docker Image 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t 399622/house-price-predictor:latest --file Dockerfile --tag my-image-name:$(date +%s)
  
    - name: Publish Docker Image
      run: |
        docker login -u 399622 -p ${{ secrets.DOCKER_HUB_TOKEN}}
        docker push 399622/house-price-predictor:latest


  
